### ISSUE TITLE
Failed to connect to camera

### ISSUE THREAD

**Issue by atirage** [hawkeye64/onvif-nvt#12]
I'm getting the following error while connecting to a camera:

ERROR  : onvif: TypeError: profiles.forEach is not a function
ERROR  : onvif:     at Camera.parseProfiles (/home/pi/.mozilla-iot/addons/onvif-adapter/node_modules/onvif-nvt/lib/camera.js:645:14)
ERROR  : onvif:     at media.getProfiles.then.results (/home/pi/.mozilla-iot/addons/onvif-adapter/node_modules/onvif-nvt/lib/camera.js:631:34)
ERROR  : onvif:     at <anonymous>
ERROR  : onvif:     at process._tickCallback (internal/process/next_tick.js:189:7)
ERROR  : onvif: TypeError: profiles.forEach is not a function
ERROR  : onvif:     at Camera.parseProfiles (/home/pi/.mozilla-iot/addons/onvif-adapter/node_modules/onvif-nvt/lib/camera.js:645:14)
ERROR  : onvif:     at media.getProfiles.then.results (/home/pi/.mozilla-iot/addons/onvif-adapter/node_modules/onvif-nvt/lib/camera.js:631:34)
ERROR  : onvif:     at <anonymous>
ERROR  : onvif:     at process._tickCallback (internal/process/next_tick.js:189:7)

As sou can see from the log I'm using the Mozilla IoT Gateway and the camera I'm using is a Raspberry Pi camera made ONVIF compatible using https://github.com/BreeeZe/rpos.

**Comment by hawkeye64** [comment]
Sounds like the Camera doesn't have profiles. Are you sure the camera is ONVIF compliant? If so, does it just have one profile that is not kept in an array? And, whast kind of camera?

**Comment by atirage** [comment]
I've added some extra logging, this is what your parseProfiles gets as argument:
{ '$': { token: 'profile_token', 
         'xmlns:tt': 'http://www.onvif.org/ver10/schema' },
Name: 'CurrentProfile',
VideoSourceConfiguration:
{ '$': { token: 'video_src_config_token' },
      Name: 'Primary Source',
      UseCount: '0',
      SourceToken: 'video_src_token',
      Bounds: { '$': [Object] } },

VideoEncoderConfiguration:
{ '$': { token: 'encoder_config_token' },
      Name: 'PiCameraConfiguration',
      UseCount: '0',
      Encoding: 'H264',
      Resolution: { Width: '1280', Height: '720' },
      Quality: '1',
      RateControl:
       { FrameRateLimit: '25',
         EncodingInterval: '1',
         BitrateLimit: '10000' },
      H264: { GovLength: '60', H264Profile: 'High' },
      Multicast: { Address: [Object], Port: '0', TTL: '1', AutoStart: 'false' },
      SessionTimeout: 'PT1000S' },

PTZConfiguration:
{ '$': { token: 'ptz_config_token_0' },
      Name: 'PTZ Configuration',
      UseCount: '1',
      NodeToken: 'ptz_node_token_0',
      DefaultAbsolutePantTiltPositionSpace: 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace',
      DefaultAbsoluteZoomPositionSpace: 'http://www.onvif.org/ver10/tptz/ZoomSpaces/PositionGenericSpace',
      DefaultRelativePanTiltTranslationSpace: 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/TranslationGenericSpace',
      DefaultRelativeZoomTranslationSpace: 'http://www.onvif.org/ver10/tptz/ZoomSpaces/TranslationGenericSpace',
      DefaultContinuousPanTiltVelocitySpace: 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/VelocityGenericSpace',
      DefaultContinuousZoomVelocitySpace: 'http://www.onvif.org/ver10/tptz/ZoomSpaces/VelocityGenericSpace',
      DefaultPTZSpeed: { PanTilt: [Object], Zoom: [Object] },
      DefaultPTZTimeout: 'PT5S' }
}

**Comment by mijapa** [comment]
I have the same error using the Mozilla IoT Gateway and the camera I'm using is Android phone camera made ONVIF compatible using IP Webcam https://play.google.com/store/apps/details?id=com.pas.webcam

**Comment by hawkeye64** [comment]
Thanks for the info. I have an Android I can use to replicate this and get it fixed (hopefully).

**Comment by atirage** [comment]
Any update on this? I'm no js expert, but to me this looks like a type mismatch: rpos provides an object, nvt expects an array.

**Comment by hawkeye64** [comment]
@atirage Sorry, have not had time. I apologize that this project is low on my list. We use it at work, but all of our cameras work with it. PRs are very welcomed if you feel you can help out. The problem with working with hardware is if you don't have the specific hardware, then you can only hope something works. This can cause several iterations with those that do have the hardware. Therefore, it's easier for those with the hardware do the specific work needed. Again, my apologies. Please feel free to work through it and make adjustments as needed. I also just want to point out, that having done this project, I have found the ONVIF specs to be lenient on design and different camera manufacturers implement in different ways, unfortunately. If you make changes, be sure to keep compatibility with those cameras that currently do work. ie: test returned object as js array or js object.. Thanks.

**Comment by atirage** [comment]
@hawkeye64, now worries, I was just wondering if it was still on your radar or not. :)
I managed to fix it by adding the following code snippet in function _parseProfiles_:
```
if (!Array.isArray(profiles)) {
      var prof_arr = [];
      prof_arr[0] = profiles;
      profiles = prof_arr;
    }
```
I'm not sure if this is generic enough, but it seems that the issue will happen only if there's just one profile.

**Comment by hawkeye64** [comment]
@atirage Yes, it should probably detect if it is an object or an array. Can you PR the code?

**Comment by atirage** [comment]
@hawkeye64, I wanted to do that, but I was not able to push my branch with the fix to the remote. 
Do I need any extra permission on your repo?

**Comment by hawkeye64** [comment]
Will release soon

**Comment by hawkeye64** [comment]
Forgot to close after releasing, so closing now
