### ISSUE TITLE
npm install results in "Appears to be a git repo or submodule."

### ISSUE THREAD

**Issue by logidelic** [hawkeye64/onvif-nvt#15]
First of all, thank you for the great module. Has been working very well for me so far!

That said, I've run into an annoying issue. When I run `npm install` for the first time, it installs the module correctly (as per `package.json`). However, if I run `npm install` again, I get the following error:

```
npm ERR! path /home/user/app/node_modules/onvif-nvt
npm ERR! code EISGIT
npm ERR! git /home/user/app/node_modules/onvif-nvt: Appears to be a git repo or submodule.
npm ERR! git     /home/user/app/node_modules/onvif-nvt
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```

If I delete `node_modules/onvif-nvt` I can run `npm install` and it will install again correctly.

I've never seen this issue with any other npm modules on any projects (and I use many). Any ideas about this? I am guessing that the repository has a `.git` file checked in somewhere that shouldn't be there...

Thank you!

**Comment by hawkeye64** [comment]
I have also never seen this issue. However, I have seen a lot of issues lately with NPM. Can you try with yarn and see if you get the same results?
