### ISSUE TITLE
The security token could not be authenticated or authorized

### ISSUE THREAD

**Issue by aectarine** [hawkeye64/onvif-nvt#506]
Hello. Im using onvif-nvt.

Client Server: 192.168.1.13 / pm2 background / use only first device variable
ONVIF-NVT Server: 192.168.0.160

It works fine at first, but after some time I get that error.

I do not create and use a new device every time,
Control using the device created first.

I'm having the following problem with internal soap communication:
What could be wrong?

![image](https://user-images.githubusercontent.com/7877350/120781428-0bc82680-c564-11eb-872c-670e7aeb562a.png)

**Comment by hawkeye64** [comment]
@aectarine No ideas atm. However, onvif-nvt is going through a complete rewrite. Just a heads-up that there are no more callbacks. Everything is now done via async/await. Once I finish the rewrite, I can look into this for older versions of the software (as the new code will be in a "next" branch).

Btw, what camera are you using?

**Comment by aectarine** [comment]
Thank you for your reply.
Im using XNP-6040H.
It works normally on a Linux system with the same 192.168.0.X IP band, but it seems that a problem occurs when running in Windows 10's CMD under different IP states of 0.X and 1.X.

**Comment by hawkeye64** [comment]
It's a little disturbing to know that it works with Linux but has issues with Windows 10. Have you looked at the responses with Wireshark per chance?

Also, I am unfamiliar with that ONVIF camera. Can you give some more details?

**Comment by aectarine** [comment]
I was wrong. After running as PM2, after some time, a 401 Unauthorized error occurs, and there is a symptom that the camera web page also has a 401 error and cannot be accessed.
I'm not sure if it's the camera's fault or if the SOAP communication error is causing the camera as well.

**Comment by hawkeye64** [comment]
@aectarine This could be caused by time drift on the camera. Make sure it has a good NTP server.

**Comment by aectarine** [comment]
Thanks for the kind and quick reply.
^_^
